# Generated by Django 4.0.4 on 2022-11-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('photo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('username', models.CharField(max_length=100, null=True)),
                ('usage', models.CharField(choices=[('P', 'Prywatne'), ('K', 'Komercyjne'), ('KO', 'Komercyjne ograniczone')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_from', models.CharField(max_length=100)),
                ('user_to', models.CharField(max_length=100)),
                ('message_text', models.CharField(blank=True, max_length=600, null=True)),
                ('negotiation_price', models.FloatField()),
                ('negotiation_usage', models.CharField(choices=[('P', 'Prywatne'), ('K', 'Komercyjne'), ('KO', 'Komercyjne ograniczone')], max_length=2)),
                ('negotiation_status', models.CharField(blank=True, choices=[('A', 'Zaakceptowana'), ('O', 'Odrzucona')], max_length=1)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
