# Generated by Django 4.0.4 on 2022-11-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('username', models.CharField(max_length=100, null=True)),
                ('usage', models.CharField(choices=[('P', 'Prywatne'), ('K', 'Komercyjne'), ('KO', 'Komercyjne ograniczone')], max_length=2)),
            ],
        ),
    ]
