# Generated by Django 4.0.4 on 2022-11-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.CharField(max_length=100)),
                ('user_to', models.CharField(max_length=100)),
                ('message_text', models.CharField(blank=True, max_length=600, null=True)),
                ('negotiation_price', models.FloatField()),
                ('negotiation_usage', models.CharField(choices=[('P', 'Prywatne'), ('K', 'Komercyjne'), ('KO', 'Komercyjne ograniczone')], max_length=2)),
                ('negotiation_status', models.CharField(choices=[('A', 'Zaakceptowana'), ('O', 'Odrzucona')], max_length=1)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
