# Generated by Django 4.0.4 on 2022-11-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='photo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_name', to='myapp.product'),
        ),
    ]
