# Generated by Django 4.0.4 on 2022-11-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_messages_message_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='negotiation_status',
            field=models.CharField(choices=[('Zaakceptowana', 'Zaakceptowana'), ('Odrzucona', 'Odrzucona'), ('Oczekująca', 'Oczekująca'), ('Kontroferta', 'Kontroferta')], default='Oczekująca', max_length=100),
        ),
    ]
