# Generated by Django 4.0.4 on 2022-11-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='negotiation_status',
            field=models.CharField(blank=True, choices=[('A', 'Zaakceptowana'), ('O', 'Odrzucona')], max_length=1),
        ),
    ]
