# Generated by Django 4.1.3 on 2022-11-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_messages_negotiation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='negotiation_status',
            field=models.CharField(choices=[('Zaakceptowana', 'Zaakceptowana'), ('Odrzucona', 'Odrzucona'), ('Oczekująca', 'Oczekująca'), ('Archiwalna', 'Archiwalna'), ('Oczekuje na wpłatę', 'Oczekuje na wpłatę')], default='Oczekująca', max_length=100),
        ),
    ]
