# Generated by Django 4.0.4 on 2022-11-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_messages_negotiation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='negotiation_status',
            field=models.CharField(choices=[('A', 'Zaakceptowana'), ('O', 'Odrzucona'), ('C', 'Oczekująca')], default='Oczekująca', max_length=1),
        ),
    ]
