# Generated by Django 4.0.4 on 2022-11-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_messages_negotiation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='negotiation_status',
            field=models.CharField(choices=[('A', 'Zaakceptowana'), ('O', 'Odrzucona'), ('C', 'Oczekująca')], default='C', max_length=1),
        ),
    ]
