# Generated by Django 4.0.4 on 2022-11-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_messages_negotiation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='negotiation_status',
            field=models.CharField(choices=[('Zaakceptowana', 'Zaakceptowana'), ('Odrzucona', 'Odrzucona'), ('Oczekująca', 'Oczekująca')], default='Oczekująca', max_length=100),
        ),
    ]
