# Generated by Django 4.0.4 on 2022-11-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_messages_negotiation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='negotiation_usage',
            field=models.CharField(choices=[('Prywatne', 'Prywatne'), ('Komercyjne', 'Komercyjne'), ('Komercyjne ograniczone', 'Komercyjne ograniczone')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage',
            field=models.CharField(choices=[('Prywatne', 'Prywatne'), ('Komercyjne', 'Komercyjne'), ('Komercyjne ograniczone', 'Komercyjne ograniczone')], max_length=100),
        ),
    ]
